# Generated by Django 2.2.6 on 2019-10-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo electronico')),
                ('username', models.CharField(max_length=50, verbose_name='Nombre de usuario')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Último login')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
